"""initial_schema

Revision ID: f3038d03c747
Revises:
Create Date: 2026-09-27 01:48:19.225987
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f3038d03c747'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('zone', sa.String(length=20), nullable=True),
    sa.Column('rack', sa.String(length=20), nullable=True),
    sa.Column('level', sa.String(length=20), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('mold_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('employee_code', sa.String(length=50), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_code')
    )
    op.create_table('mold_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('default_location_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['default_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['mold_models.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity', sa.String(length=100), nullable=False),
    sa.Column('before', sa.Text(), nullable=True),
    sa.Column('after', sa.Text(), nullable=True),
    sa.Column('reason', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('authorized_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('authorized', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('authorized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_authorized_devices_user_id'), 'authorized_devices', ['user_id'], unique=False)
    op.create_table('login_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('csrf_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_login_sessions_user_id'), 'login_sessions', ['user_id'], unique=False)
    op.create_table('molds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('original_code', sa.String(length=100), nullable=True),
    sa.Column('set_id', sa.Integer(), nullable=False),
    sa.Column('size_label', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('current_location_id', sa.Integer(), nullable=False),
    sa.Column('custodian_person_id', sa.Integer(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['current_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['custodian_person_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['set_id'], ['mold_sets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_molds_set_id'), 'molds', ['set_id'], unique=False)
    op.create_index('uq_current_set_size', 'molds', ['set_id', 'size_label'], unique=True, postgresql_where=sa.text('is_current IS TRUE'), sqlite_where=sa.text('is_current IS 1'))
    op.create_table('operations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(length=60), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('target_location_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['authorized_devices.id'], ),
    sa.ForeignKeyConstraint(['target_location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    op.create_table('operation_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operation_id', sa.Integer(), nullable=False),
    sa.Column('mold_id', sa.Integer(), nullable=False),
    sa.Column('before_status', sa.String(length=30), nullable=False),
    sa.Column('after_status', sa.String(length=30), nullable=False),
    sa.Column('before_location_id', sa.Integer(), nullable=False),
    sa.Column('after_location_id', sa.Integer(), nullable=False),
    sa.Column('before_custodian_id', sa.Integer(), nullable=True),
    sa.Column('after_custodian_id', sa.Integer(), nullable=True),
    sa.Column('before_version', sa.Integer(), nullable=False),
    sa.Column('after_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['after_custodian_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['after_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['before_custodian_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['before_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['mold_id'], ['molds.id'], ),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operation_items_operation_id'), 'operation_items', ['operation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operation_items_operation_id'), table_name='operation_items')
    op.drop_table('operation_items')
    op.drop_table('operations')
    op.drop_index('uq_current_set_size', table_name='molds', postgresql_where=sa.text('is_current IS 1'), sqlite_where=sa.text('is_current IS 1'))
    op.drop_index(op.f('ix_molds_set_id'), table_name='molds')
    op.drop_table('molds')
    op.drop_index(op.f('ix_login_sessions_user_id'), table_name='login_sessions')
    op.drop_table('login_sessions')
    op.drop_index(op.f('ix_authorized_devices_user_id'), table_name='authorized_devices')
    op.drop_table('authorized_devices')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_table('mold_sets')
    op.drop_table('people')
    op.drop_table('mold_models')
    op.drop_table('locations')
    # ### end Alembic commands ###
